import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:doc_pilot_new_app_gradel_fix/models/pdf_settings.dart';

/// Service for generating PDF documents from prescription and summary data
class PdfService {
  /// Generates a basic PDF prescription document
  ///
  /// Takes the [prescriptionText] and [patientName] (optional) and creates
  /// a professionally formatted PDF document.
  ///
  /// Returns the file path of the generated PDF.
  Future<String> generatePrescriptionPdf({
    required String prescriptionText,
    String? patientName,
  }) async {
    final pdf = pw.Document();

    // Parse the prescription text to extract sections
    final sections = _parseMarkdownToPdfContent(prescriptionText);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              _buildHeader(),
              pw.SizedBox(height: 20),

              // Patient Info (if provided)
              if (patientName != null) ...[
                _buildPatientInfo(patientName),
                pw.SizedBox(height: 20),
              ],

              // Prescription Content
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: sections,
                ),
              ),

              // Footer
              pw.SizedBox(height: 20),
              _buildFooter(),
            ],
          );
        },
      ),
    );

    // Save the PDF to a file
    final directory = await getApplicationDocumentsDirectory();
    final fileName = 'prescription_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final filePath = '${directory.path}/$fileName';
    final file = File(filePath);
    await file.writeAsBytes(await pdf.save());

    return filePath;
  }

  /// Builds the header section of the PDF
  pw.Widget _buildHeader() {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 10),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(
            color: PdfColors.deepPurple,
            width: 2,
          ),
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'MEDICAL PRESCRIPTION',
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.deepPurple,
            ),
          ),
          pw.SizedBox(height: 5),
          pw.Text(
            'Generated by DocPilot AI',
            style: const pw.TextStyle(
              fontSize: 12,
              color: PdfColors.grey700,
            ),
          ),
          pw.Text(
            'Date: ${_formatDate(DateTime.now())}',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey600,
            ),
          ),
        ],
      ),
    );
  }

  /// Builds the patient information section
  pw.Widget _buildPatientInfo(String patientName) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey200,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Row(
        children: [
          pw.Text(
            'Patient: ',
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.Text(
            patientName,
            style: const pw.TextStyle(
              fontSize: 12,
            ),
          ),
        ],
      ),
    );
  }

  /// Builds the footer section with disclaimer
  pw.Widget _buildFooter() {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 10),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(
            color: PdfColors.grey400,
            width: 1,
          ),
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Important Notice:',
            style: pw.TextStyle(
              fontSize: 9,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.red,
            ),
          ),
          pw.SizedBox(height: 3),
          pw.Text(
            'This prescription was generated using AI assistance and should be reviewed by a licensed healthcare professional before use. Do not use this as a substitute for professional medical advice.',
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey700,
            ),
          ),
          pw.SizedBox(height: 10),
          pw.Text(
            'Generated by DocPilot - AI-Powered Medical Documentation Assistant',
            style: const pw.TextStyle(
              fontSize: 8,
              color: PdfColors.grey600,
            ),
          ),
        ],
      ),
    );
  }

  /// Parses markdown-style text into PDF widgets
  List<pw.Widget> _parseMarkdownToPdfContent(String text) {
    final lines = text.split('\n');
    final widgets = <pw.Widget>[];

    for (final line in lines) {
      if (line.trim().isEmpty) {
        widgets.add(pw.SizedBox(height: 5));
        continue;
      }

      // Headers (## or ### or #)
      if (line.startsWith('###')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 10, bottom: 5),
            child: pw.Text(
              line.replaceFirst('###', '').trim(),
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.deepPurple800,
              ),
            ),
          ),
        );
      } else if (line.startsWith('##')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 12, bottom: 6),
            child: pw.Text(
              line.replaceFirst('##', '').trim(),
              style: pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.deepPurple,
              ),
            ),
          ),
        );
      } else if (line.startsWith('#')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 15, bottom: 8),
            child: pw.Text(
              line.replaceFirst('#', '').trim(),
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.deepPurple,
              ),
            ),
          ),
        );
      }
      // Bullet points
      else if (line.trim().startsWith('*') || line.trim().startsWith('-')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 15, top: 3, bottom: 3),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('• ', style: const pw.TextStyle(fontSize: 11)),
                pw.Expanded(
                  child: pw.Text(
                    line.replaceFirst(RegExp(r'^[\s\*\-]+'), '').trim(),
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ),
              ],
            ),
          ),
        );
      }
      // Numbered lists
      else if (RegExp(r'^\d+\.').hasMatch(line.trim())) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 15, top: 3, bottom: 3),
            child: pw.Text(
              line.trim(),
              style: const pw.TextStyle(fontSize: 11),
            ),
          ),
        );
      }
      // Bold text (**text**)
      else if (line.contains('**')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 3, bottom: 3),
            child: pw.RichText(
              text: _parseStyledText(line),
            ),
          ),
        );
      }
      // Regular paragraph
      else {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 3, bottom: 3),
            child: pw.Text(
              line.trim(),
              style: const pw.TextStyle(fontSize: 11),
            ),
          ),
        );
      }
    }

    return widgets;
  }

  /// Parses styled text (bold) for PDF rendering
  pw.TextSpan _parseStyledText(String text) {
    final spans = <pw.InlineSpan>[];
    final parts = text.split('**');

    for (int i = 0; i < parts.length; i++) {
      if (i % 2 == 0) {
        // Regular text
        spans.add(
          pw.TextSpan(
            text: parts[i],
            style: const pw.TextStyle(fontSize: 11),
          ),
        );
      } else {
        // Bold text
        spans.add(
          pw.TextSpan(
            text: parts[i],
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        );
      }
    }

    return pw.TextSpan(children: spans);
  }

  /// Formats a DateTime object into a readable string
  String _formatDate(DateTime date) {
    final months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ];

    return '${months[date.month - 1]} ${date.day}, ${date.year}';
  }
}
